default: &default
  username: postgres
  password: 111

development:
  <<: *default
  adapter: postgresql
  database: travis_development
  pool: 5
  timeout: 5000
  port: 5432

test:
  <<: *default
  adapter: postgresql
  database: travis_test
  pool: 5
  timeout: 5000
  port: 5432

production:
  <<: *default
  adapter: postgresql
  database: travis_production
  pool: 5
  timeout: 5000
  port: 5432